### ISSUE TITLE
Fusion360 files for the design

### ISSUE THREAD

**Issue by jschrier** [rodolfokeesey/Liquid-Handler#10]
@rodolfokeesey — I had thought that the `3D_Assets` contained the Fusion360 file, but this does not appear to be present.  Can you upload this?  We have an engineering student coming on, who is going to work on modifying the design.

**Comment by rodolfokeesey** [comment]
Can do! Out traveling, but I will try to get STEP files in today, and F360 files once I get to a machine with access to it.

**Comment by rodolfokeesey** [comment]
Ok! f360 files and STEP files are included for all the 3D models. A google drive link was also added containing .STEP and .f360 files of the fully assembled Sidekick.
