### ISSUE TITLE
Question Re License

### ISSUE THREAD

**Issue by LRParser** [rodolfokeesey/Liquid-Handler#3]
This looks like a great project! I don’t see any license listed, though. Are there certain restrictions on who is allowed to build it or needing to pay for a license? I’d like to try the build myself.

**Comment by rodolfokeesey** [comment]
Ah, good question. This project is licensed under CERN-OHL-P. I will add that to the repo, thanks for pointing that out! Feel free to build away, and let us know if you have any issues.

**Comment by jschrier** [comment]
CERN license.txt file added in https://github.com/rodolfokeesey/Liquid-Handler/commit/c5c9747b9969300679b8b78373d74018e33a4041
