### ISSUE TITLE
[HARDWARE]: Where can i buy the LPM pump? The only way i can found is texting with company supporter. Are there anyway to buy its?

### ISSUE THREAD

**Issue by Binh2542** [rodolfokeesey/Liquid-Handler#8]
[HARDWARE]: Where can i buy the LPM pump? The only way i can found is texting with company supporter. Are there anyway to buy its?

**Comment by jschrier** [comment]
Correct.  You must contact [Lee Company](https://www.theleeco.com/) to purchase the LMP pumps.  They are the only vendor.

**Comment by jschrier** [comment]
Possible alternatives (which we haven't tried yet): Takasago Fluidics  https://www.takasago-fluidics.com/products/mcp?variant=34641036279974   These are roughly $200 ea, so it does not reduce costs.
